[general]
import = [
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

[window]
padding = { x = 6, y = 3 }
opacity = 0.75
blur = true

[scrolling]
history = 100000
multiplier = 5

[font]
offset = { x = 0, y = 6 }

[colors.primary]
background = "#000000"
